### ISSUE TITLE
错误信息

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#25]
游戏中无法看到别的玩家血条，这样PK时唯一能看的就是对方躺下没躺下。
服务端以及LIB资源工具巨卡，是不是弄个多线程或者优化一下？
游戏中比奇仓库位置邮寄时勾选邮票无反应，邮票检测失效了。
登陆器更新地址改成127.0.0.1后，错误提示错误。更新地址开通他会更新，连接失败提示：无法获取游戏补丁。而类似127.0.0.1无法连接的他应该提示：无法获取游戏补丁    而不是如下大量提示错误

[2024/7/23 9:36:29] System.AggregateException: One or more errors occurred. (由于目标计算机积极拒绝，无法连接。 (127.0.0.1:80))
 ---> System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:80)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Launcher.AMain.Download(String fileName) in E:\传奇\mir2-main\Client\Forms\AMain.cs:line 355
   at Launcher.AMain.GetOldFileList() in E:\传奇\mir2-main\Client\Forms\AMain.cs:line 159
   at Launcher.AMain.Start() in E:\传奇\mir2-main\Client\Forms\AMain.cs:line 63

**Comment by angelk727** [comment]
血条不解释官方也这样
服务器怎样卡？工具怎样卡？你说的很抽象。
邮票一直未定义，也没多大意义。应该可以通过NPC脚本就能实现！最关键的是我也没玩过韩服不知道这东西是做什么的！
登录器之所以改为127.0.0.1是因为不改会自动更新水晶端，如果你想开启更新功能，请将登录器窗口界面改回水晶端并修改为你自己的更新地址。

**Comment by angelk727** [comment]
Hero attack mode error 其实这个不是错误，而是人家没有定义
It is suggested to increase database search 这个你就更别想了，旧的其实人家屏蔽了就是没有删除而已
