### ISSUE TITLE
@GIVESKILL错误

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#30]
@GIVESKILL   玩家名   基本剑术    （服务器崩溃）
@GIVESKILL   玩家名   基本剑术    3   （服务器崩溃）
@GIVESKILL   玩家名   1    （服务器崩溃）

@GIVESKILL   玩家名   1     3    （正常）

以上三种即使不对也不至于导致崩溃啊....外部循环错误

**Comment by angelk727** [comment]
在水晶原版上崩溃吗？

**Comment by Jinspang** [comment]
你那边无崩溃？不能啊，莫非我改代码改的？我也没动这个命令有关的啊，我有你的原始服务端和客户端也测试了，下了你今天的最新源码，生成后放进去也是崩溃，外部循环错误。我换个电脑再试试

**Comment by Jinspang** [comment]
[2024/8/7 17:19:35]: [外循环错误 线程 221]System.NullReferenceException: Object reference not set to an instance of an object.
   at Server.MirDatabase.UserMagic.GetDelay() in E:\传奇\Server.rar等3个文件\mir2-main\Server\MirDatabase\MagicInfo.cs:line 221
   at Server.MirObjects.PlayerObject.StopGame(Byte reason) in E:\传奇\Server.rar等3个文件\mir2-main\Server\MirObjects\PlayerObject.cs:line 345
   at Server.MirNetwork.MirConnection.SoftDisconnect(Byte reason) in E:\传奇\Server.rar等3个文件\mir2-main\Server\MirNetwork\MirConnection.cs:line 739
   at Server.MirNetwork.MirConnection.SendDisconnect(Byte reason) in E:\传奇\Server.rar等3个文件\mir2-main\Server\MirNetwork\MirConnection.cs:line 796
   at Server.MirEnvir.Envir.WorkLoop() in E:\传奇\Server.rar等3个文件\mir2-main\Server\MirEnvir\Envir.cs:line 683

**Comment by Jinspang** [comment]
找到问题了 ，玩家名字不能是  111   222   名字111   222 就崩溃。除了这俩都没事...........

**Comment by angelk727** [comment]
很好的问题，值得修复，这BUG虽然很好解决。但最好还是提交给水晶从源头修复

**Comment by Jinspang** [comment]
我懒得搭理他们，你看看论坛好多老外说咱们中国人只会去拿东西，从不贡献。他们却忘了是多少中国人提出了BUG。我也很想笑。他们源代码都是公开的，有什么好拿的。。。
